Webpack dev server improvements.
wictorwilen/generator-teams-tab pull request #251
Opened 2021-10-13 20:21 UTC by s-KaiNet

Based on the outcome of the discussion [here](https://github.com/pnp/generator-teams/discussions/248#discussioncomment-1465530): 

- `devServer` options were moved to the `webpack.client.js`
- notification about starting the compilation

Also:
- during `-serve` without `--debug` liveReload and overlay for devServer is disabled (otherwise it creates very strange issues like infinite page reloading)
- I could not disable `webpack:client` in `--debug` mode, because another task `static:inject` depends on the output from `webpack:client`. When `webpack:client` is disabled, `static:inject` will produce the wrong output and will break everything (though the build looks ok, the app doesn't work)

/cc @pschaeflein

2021-10-13 21:49 UTC, pschaeflein commented
Thanks!

2021-10-14 06:57 UTC, wictorwilen commented
Thanks @s-KaiNet. Works great for debug builds, but as per discussion, the `gulp serve` command without debug should build and serve as if it was in production, as per the discussion. This PR will always run the webpack devserver, which is not needed and should not be run in production mode.

2021-10-14 07:48 UTC, s-KaiNet commented
I haven't found that we agreed on such a requirement, but it's not an issue, I can update the PR. However, I have a couple of questions:
- in the version `3.2.0` when you run `gulp serve` at the very end it starts the `watch` task, which re-builds both server and client bundles on a file change. When I change a client file, it rebuilds the whole client bundle by running `webpack:client` task. This is the behavior in the previous version, `3.2.0`. The current behavior is exactly the same as it was before - but instead of `webpack:client` it uses webpack-dev-server for the same purpose (rebuilds client build). Now you're asking about changing the default behavior for the current version and previous versions (which might not be desired for some users). Is it correct?
- You said we don't need webpack devserver when running in production. In that case, the whole `watch` task in `gulp serve` (without `--debug`) doesn't make sense. Does anybody need file watchers and rebuilds on file change when running in production? I don't think so. For me, the better idea is just completely disable `watch` task when running `gulp serve` aka "production serve". 
- what is the correlation between `gulp serve` and `npm run start` (`node dist/server.js`)? I thought that the latter one is supposed to be run in production, because it starts a new nodejs based web server, which serves all files. In other words, why do you need `gulp serve` if you have `npm run start`?

2021-10-14 11:27 UTC, wictorwilen commented
> * in the version `3.2.0` when you run `gulp serve` at the very end it starts the `watch` task, which re-builds both server and client bundles on a file change. When I change a client file, it rebuilds the whole client bundle by running `webpack:client` task. This is the behavior in the previous version, `3.2.0`. The current behavior is exactly the same as it was before - but instead of `webpack:client` it uses webpack-dev-server for the same purpose (rebuilds client build). Now you're asking about changing the default behavior for the current version and previous versions (which might not be desired for some users). Is it correct?

What I meant that `gulp serve` should be running as when in production, that is webpack devserver should not be used. Essentially no change to that.

> * You said we don't need webpack devserver when running in production. In that case, the whole `watch` task in `gulp serve` (without `--debug`) doesn't make sense. Does anybody need file watchers and rebuilds on file change when running in production? I don't think so. For me, the better idea is just completely disable `watch` task when running `gulp serve` aka "production serve".

When running in production you likely don't need the file watchers, that is correct. But removing that "feature" should be out of scope for this PR. And, I've previously taken advantage of this "feature" in demo apps deployed to Azure, where I could directly update the files using the App Service Editor.

> * what is the correlation between `gulp serve` and `npm run start` (`node dist/server.js`)? I thought that the latter one is supposed to be run in production, because it starts a new nodejs based web server, which serves all files. In other words, why do you need `gulp serve` if you have `npm run start`?

This is absolutely correct. When you have deployed this into production you likely run `npm run start` or `node dist/server.js` in your container or web application and not `gulp serve`. Gulp etc. shouldn't even be deployed to a production build. However there are many scenarios where you want to mimic a production build on your local machine, that's where `gulp serve` without the `debug` parameter makes sense.

2021-10-14 20:35 UTC, s-KaiNet commented
Thank you for clarifying all the things! Sorry if I'm asking too many dumb questions :). I just want to better understand how everything works to have fewer questions in the future doing other potential contributions. 

I updated the PR and changed the behavior in "serve" mode:
- `gulp serve --debug` starts webpack dev server, reload and rebuild on a client file change, etc...
- `gulp serve` now behaves exactly like it was before (3.2.0) - it doesn't use a webpack dev server.

2021-10-15 06:10 UTC, wictorwilen commented
Thanks @s-KaiNet - I'll review this today

2021-10-15 07:20 UTC, wictorwilen requested changes
Great stuff, works as expected. Please check the comments and also add entries in the change log files in the generator and the deploy package folders (as Unreleased versions)

2021-10-15 07:20 UTC, wictorwilen commented on packages/yoteams-build-core/src/webpackServe.ts
>      const webpackConfig = require(path.join(process.cwd(), "webpack.config"));
We need a *default* webpack dev server setting here. The scenario is that you scaffolded a project with an earlier version of yo teams and upgrade to this package. Then the hot-reloading does not work. So just a bare minimum config that is used if the `devServer` config is missing.

2021-10-15 07:20 UTC, wictorwilen commented on packages/yoteams-build-core/src/webpackServe.ts
> +        console.log("webpack compiling");
Please use the `fancy-log` module as done in the rest of the tasks

2021-10-15 07:25 UTC, s-KaiNet commented on packages/yoteams-build-core/src/webpackServe.ts
> +        console.log("webpack compiling");
The reason why I don't use fancy-log here is to be consistent with other webpack messages. I.e. `webpack compiled in 990 ms` is an OOB webpack message without fancy-log (and we cannot change it).
![image](https://user-images.githubusercontent.com/10658276/137448267-c8dee97c-a7d2-4575-a4f9-19aedee10653.png)
Should I change it to fancy-log anyway?

2021-10-15 07:50 UTC, wictorwilen commented on packages/yoteams-build-core/src/webpackServe.ts
> +        console.log("webpack compiling");
I'd prefer to use it for the sake of consistency. As you say, other modules use different logging mechanisms (webpack, linter etc), but the things we can control should use the same

2021-10-15 07:55 UTC, s-KaiNet commented
Will update the change log in a minute.

2021-10-15 09:20 UTC, wictorwilen approved these changes
Awesome job! Thanks!

2021-10-15 09:21 UTC, merged